# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
black: false
check_commit_message: true
cherry_pick_automation: true
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: true
docs_test: true
plugin_app_label: rpm
plugin_camel: PulpRpm
plugin_camel_short: Rpm
plugin_caps: PULP_RPM
plugin_caps_short: RPM
plugin_dash: pulp-rpm
plugin_dash_short: rpm
plugin_name: pulp_rpm
plugin_snake: pulp_rpm
pulp_settings: null
pulpcore_branch: master
pulpcore_pip_version_specifier: null
pydocstyle: true
pypi_username: pulp
redmine_project: pulp_rpm
stable_branch: '3.4'
test_bindings: false
test_performance:
- sync
- publish
- pulp_to_pulp
test_s3: true
travis_addtl_services: []
travis_notifications: None
update_redmine: true 

