# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
additional_repos: []
black: true
check_commit_message: true
check_gettext: true
check_manifest: true
check_openapi_schema: true
check_stray_pulpcore_imports: true
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: true
docs_test: true
issue_tracker: redmine
plugin_app_label: rpm
plugin_camel: PulpRpm
plugin_camel_short: Rpm
plugin_caps: PULP_RPM
plugin_caps_short: RPM
plugin_dash: pulp-rpm
plugin_dash_short: rpm
plugin_default_branch: master
plugin_name: pulp_rpm
plugin_snake: pulp_rpm
publish_docs_to_pulpprojectdotorg: true
pulp_scheme: https
pulp_settings:
  allowed_content_checksums:
  - sha1
  - sha224
  - sha256
  - sha384
  - sha512
  allowed_export_paths:
  - /tmp
  allowed_import_paths:
  - /tmp
pulpcore_branch: master
pulpcore_pip_version_specifier: null
pulpprojectdotorg_key_id: aa499d7938ed
pydocstyle: true
pypi_username: pulp
redmine_project: pulp_rpm
release_user: pulpbot
test_bindings: false
test_cli: true
test_fips_nightly: false
test_performance:
- sync
- publish
- pulp_to_pulp
test_released_plugin_with_next_pulpcore_release: false
test_s3: true
update_redmine: true
upgrade_range: []

